#!/usr/bin/env python -dOt
'''
OpenCL Toolbox - Bundle of scripts to make OpenCL easier.
Copyright (C) 2016  Sean ZO Marciniak

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

'''
import os, sys
import getopt
try:
    import pyopencl as cl
except ImportError:
    print "pyopencl is not installed"
    sys.exit(-1)

'''
    In order to create context without user prompt,
    it will create context on the default Opencl device
    for the given system.
'''

os.environ["PYOPENCL_CTX"] = '0:0'

if __name__ == "__main__":
    options, files  = getopt.getopt(sys.argv[1:], ':w')
    for opt, args in options:
        if opt == '-w':
            os.environ["PYOPENCL_COMPILER_OUTPUT"] = '1'
    try:
        ctx = cl.create_some_context()
    except cl.Error as e:
        print "Error is: ", e
        sys.exit(1)
    if len(files) == 0:
        print "Usage: {} [-w] file(s) ...".format(sys.argv[0])
        sys.exit(1)
    for kernel_file in files:
        try:
            cl.Program(ctx, open( kernel_file ,'r').read()).build()
        except (cl.Error, RuntimeError, IOError) as e:
            print kernel_file , e
